/*
 *    Index file for node application, initializes React components.
 *    Generated by Create Node App package. No changes should need to be made to this file unless
 *    a low-level component is required to be run from the index file.
 */

import React from "react";
import ReactDOM from "react-dom/client";
import "./css/index.css";
import App from "./App";

const root = ReactDOM.createRoot(document.getElementById("root")!);
root.render(
    <React.StrictMode>
        <App />
    </React.StrictMode>
);
